---
- hosts: all
  sudo: true
  vars:

    - psql_db: crowd
    - psql_localhost_method: trust

    # Uncomment these to do full setup
    #- crowd_license: "YOUR_LICENSE_WITHOUT_NEWLINES"
    #- crowd_admin_passwd: "A_SECURE_PASSWORD"

  roles:

    - postgres

    # 1st run does full setup in devmode
    #- { role: crowd, crowd_setup: true }
    # 2nd reverts to non-devmode
    - role: crowd
