---

- name: Setup environment
  lineinfile: dest=/etc/environment line="{{item}}"
  with_items:
    - "LANGUAGE=en_US.UTF-8"
    - "LC_ALL=en_US.UTF-8"


- name: Install basic packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python-pycurl
    - git
    - tmux
    - gpm
    - ack-grep

# This comes from dataserver now.
#- name: Make Atlassian directories
#
#  file:
#    path: /opt/atlassian
#    state: directory
#    mode: 0755
#
#  file:
#    path: /var/atlassian
#    state: directory
#    mode: 0755
    

- name: Download Netdata installer
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /tmp/netdata-kickstart.sh


- name: Install Netdata
  command: sh netdata-kickstart.sh all --non-interactive creates=/usr/sbin/netdata chdir=/tmp

#- name: "Build hosts file"
#  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
#  when: hostvars[item].ansible_eth1_ipv4.address is defined
#  with_items: dataserver

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts line="{{item}}"
  with_items:
    - "192.168.2.29     dataserver      dataserver.avva"
