---
- hostname:
    name: confluence

- name: Install Confluence dependencies
  apt: pkg=git,curl state=installed

- name: Create base directory
  file: path={{confluence_base}} state=directory

- name: Fetch Confluence
  get_url: 
    url=https://www.atlassian.com/software/confluence/downloads/binary/{{confluence_tar}}
    dest={{confluence_base}}/{{confluence_tar}}

- name: Unpack Confluence
  command: 
    creates={{confluence_dir}}
    chdir={{confluence_base}}
    tar zxf {{confluence_tar}}


- name: Create user
  user: 
    name={{confluence_user}}
    home={{confluence_home}}
    createhome=true


- name: Fix permissions for working directories
  file: path={{confluence_base}}/{{confluence_dir}}/{{item}} owner={{confluence_user}} state=directory recurse=true
  with_items:
    - logs
    - temp
    - work


- name: Create config directory
  file: path={{confluence_home}}/shared/ state=directory owner={{confluence_user}}

- name: Symlink install to current
  command:
    chdir={{confluence_base}}
    ln -sf {{confluence_dir}} current

- name: Correct Confluence home
  blockinfile:
          dest: /opt/atlassian/confluence/current/confluence/WEB-INF/classes/confluence-init.properties
          marker: "# Managed with AVVA: https://bitbucket.org/wkennedy/avva/"
          insertafter: "#confluence.home=/var/confluence-home"
          content: |
              confluence.home=/var/atlassian/confluence


- name: Install systemd unit
  template:
    src=confluence.service.j2
    dest=/etc/systemd/system/confluence.service
  register: svc

- name: Enable
  shell: systemctl daemon-reload ; systemctl enable confluence.service

- name: Start Confluence
  shell: service confluence start


- name: Create Admin user
  command: >
     curl -H 'Content-Type: application/json' --data '' \
          --user admin:admin \
          'http://localhost:8090/rest/api/1.0/admin/users?name={{confluence_admin_user}}&password={{confluence_admin_passwd}}&displayName=AdminUser&emailAddress=root@localhost'
  when: confluence_setup

- name: Set Admin user permissions
  command: >
     curl -H 'Content-Type: application/json' --data '' \
          --user admin:admin \
          --request PUT \
          'http://localhost:8090/rest/api/1.0/admin/permissions/users?permission=SYS_ADMIN&name={{confluence_admin_user}}'
  when: confluence_setup
