---

- name: Install Postgres
  apt: pkg=postgresql-{{ psql_version }} state=installed

- name: Configure DB access
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{ psql_version }}/main/pg_hba.conf

- name: Restart service postgres, in all cases
  service:
    name: postgresql
    state: restarted

- postgresql_user:
    login_host: localhost
    login_user: postgres
    name: "{{ item }}" 
    password: "{{ item }}"
    role_attr_flags: LOGIN,CREATEDB
    state: present
  with_items:
        - jira
        - bitbucket
        - confluence
        - bamboo
        - crowd
        - fisheye
        - crucible

- postgresql_db:
    db: "{{ item }}"
    encoding: UTF-8
    login_host: localhost
    login_user: postgres
    owner: "{{ item }}"
    template: template0
  with_items: 
        - jira
        - bitbucket
        - confluence
        - bamboo
        - crowd
        - fisheye
        - crucible

