---
- hostname:
        name: fisheye

- name: Install Fisheye dependencies
  apt: pkg=git,curl,unzip state=installed

- name: Create base directory
  file: path={{fisheye_base}} state=directory

- name: Fetch Fisheye
  get_url: 
    url=https://product-downloads.atlassian.com/software/fisheye/downloads/{{fisheye_tar}}
    dest={{fisheye_base}}/{{fisheye_tar}}

- name: Unpack Fisheye
  command: 
    creates={{fisheye_dir}}
    chdir={{fisheye_base}}
    unzip {{fisheye_tar}}


- name: Create user
  user: 
    name={{fisheye_user}}
    home={{fisheye_home}}
    createhome=true


- name: Fix permissions for working directories
  file: path=/opt/atlassian owner={{fisheye_user}} state=directory recurse=true

- name: Fix permissions for working directories
  file: path=/var/atlassian owner={{fisheye_user}} state=directory recurse=true


- name: Create config directory
  file: path={{fisheye_home}}/shared/ state=directory owner={{fisheye_user}}


- name: Symlink install to current
  command:
    chdir={{fisheye_base}}
    ln -sf {{fisheye_dir}} current


- name: Install systemd unit
  template:
    src=fisheye.service.j2
    dest=/etc/systemd/system/fisheye.service
  register: svc


- name: Enable Fisheye service
  systemd:
    name: fisheye
    state: reloaded
    enabled: yes

