---
- hostname:
   name: bitbucket

- name: Install Bitbucket dependencies
  apt: pkg=git,curl state=installed

- name: Create base directory
  file: path={{bitbucket_base}} state=directory

- name: Fetch Bitbucket
  get_url: 
    url=https://www.atlassian.com/software/stash/downloads/binary/{{bitbucket_tar}}
    dest={{bitbucket_base}}/{{bitbucket_tar}}

- name: Unpack Bitbucket
  command: 
    creates={{bitbucket_dir}} chdir={{bitbucket_base}}
    unarchive {{bitbucket_tar}}


- name: Create user
  user: 
    name={{bitbucket_user}}
    home={{bitbucket_home}}
    createhome=true


- name: Fix permissions for working directories
  file: path={{bitbucket_base}}/{{bitbucket_dir}}/{{item}} owner={{bitbucket_user}} state=directory recurse=true
  with_items:
    - logs
    - temp
    - work


- name: Create config directory
  file: path={{bitbucket_home}}/shared/ state=directory owner={{bitbucket_user}}

- name: Install default config
  template: src="bitbucket-config.properties.j2" dest="{{bitbucket_home}}/shared/bitbucket-config.properties"


- name: Symlink install to current
  command:
    chdir={{bitbucket_base}}
    ln -sf {{bitbucket_dir}} current


- name: Set JRE_HOME in set-jre-home.sh
  lineinfile:
          path: /opt/atlassian/bitbucket/current/bin/set-jre-home.sh
          insertbefore: BOF
          line: "JRE_HOME=/usr/lib/jvm/oracle-java8-server-jre-amd64/jre"


- name: Install systemd unit
  template:
    src=bitbucket.service.j2
    dest=/etc/systemd/system/bitbucket.service
  register: svc


- name: Enable and start Bitbucket
  service:
    name: bitbucket
    enabled: yes
    state: started

