---

- name: Create opt/java

  file:
    path: /opt/java
    state: directory
    mode: 0755


#- name: Install AdoptOpenJDK 11
#
#  unarchive:
#    src: "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jre_x64_linux_hotspot_11.0.2_9.tar.gz"
#    dest: "/opt/java/"
#    copy: no

- name: Install Oracle Java 8u162
  apt:
    deb: /vagrant/debian/oracle-java8-server-jre_8u162_amd64.deb
